// Generated by scripts/update-globe-data.ts
// Generated At: 2026-03-18T21:34:38.431Z

import type { MarkerEntry } from "../globe/types/globe.types";

export const CANONICAL_MARKERS: MarkerEntry[] = [
  {
    "tz": "Africa/Abidjan",
    "coords": [
      5.32,
      -4.03
    ],
    "etcgmtOffsetKey": "UTC+00:00"
  },
  {
    "tz": "Africa/Accra",
    "coords": [
      5.56,
      -0.2
    ],
    "etcgmtOffsetKey": "UTC+00:00"
  },
  {
    "tz": "Africa/Addis_Ababa",
    "coords": [
      9.02,
      38.75
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Africa/Algiers",
    "coords": [
      36.75,
      3.06
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Africa/Cairo",
    "coords": [
      30.04,
      31.24
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Africa/Casablanca",
    "coords": [
      33.59,
      -7.62
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Africa/Dar_es_Salaam",
    "coords": [
      -6.79,
      39.28
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Africa/Johannesburg",
    "coords": [
      -26.2,
      28.04
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Africa/Kampala",
    "coords": [
      0.35,
      32.58
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Africa/Khartoum",
    "coords": [
      15.5,
      32.56
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Africa/Kinshasa",
    "coords": [
      -4.32,
      15.31
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Africa/Lagos",
    "coords": [
      6.45,
      3.4
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Africa/Luanda",
    "coords": [
      -8.84,
      13.23
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Africa/Maputo",
    "coords": [
      -25.97,
      32.58
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Africa/Nairobi",
    "coords": [
      -1.29,
      36.82
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Africa/Tripoli",
    "coords": [
      32.9,
      13.18
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Africa/Tunis",
    "coords": [
      36.81,
      10.18
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "America/Adak",
    "coords": [
      51.88,
      -176.66
    ],
    "etcgmtOffsetKey": "UTC-10:00"
  },
  {
    "tz": "America/Anchorage",
    "coords": [
      61.22,
      -149.9
    ],
    "etcgmtOffsetKey": "UTC-09:00"
  },
  {
    "tz": "America/Argentina/Buenos_Aires",
    "coords": [
      -34.6,
      -58.38
    ],
    "etcgmtOffsetKey": "UTC-03:00"
  },
  {
    "tz": "America/Argentina/Cordoba",
    "coords": [
      -31.42,
      -64.18
    ],
    "etcgmtOffsetKey": "UTC-03:00"
  },
  {
    "tz": "America/Asuncion",
    "coords": [
      -25.26,
      -57.58
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Atikokan",
    "coords": [
      48.76,
      -91.62
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Bahia",
    "coords": [
      -12.97,
      -38.51
    ],
    "etcgmtOffsetKey": "UTC-03:00"
  },
  {
    "tz": "America/Belem",
    "coords": [
      -1.46,
      -48.5
    ],
    "etcgmtOffsetKey": "UTC-03:00"
  },
  {
    "tz": "America/Bogota",
    "coords": [
      4.71,
      -74.07
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Boise",
    "coords": [
      43.62,
      -116.2
    ],
    "etcgmtOffsetKey": "UTC-07:00"
  },
  {
    "tz": "America/Campo_Grande",
    "coords": [
      -20.44,
      -54.65
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Cancun",
    "coords": [
      21.16,
      -86.85
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Caracas",
    "coords": [
      10.49,
      -66.88
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Chicago",
    "coords": [
      41.88,
      -87.63
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "America/Chihuahua",
    "coords": [
      28.63,
      -106.09
    ],
    "etcgmtOffsetKey": "UTC-07:00"
  },
  {
    "tz": "America/Costa_Rica",
    "coords": [
      9.93,
      -84.08
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "America/Cuiaba",
    "coords": [
      -15.6,
      -56.1
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Denver",
    "coords": [
      39.74,
      -104.98
    ],
    "etcgmtOffsetKey": "UTC-07:00"
  },
  {
    "tz": "America/Detroit",
    "coords": [
      42.33,
      -83.05
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Edmonton",
    "coords": [
      53.55,
      -113.49
    ],
    "etcgmtOffsetKey": "UTC-07:00"
  },
  {
    "tz": "America/El_Salvador",
    "coords": [
      13.69,
      -89.22
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "America/Fortaleza",
    "coords": [
      -3.72,
      -38.53
    ],
    "etcgmtOffsetKey": "UTC-03:00"
  },
  {
    "tz": "America/Guatemala",
    "coords": [
      14.64,
      -90.51
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "America/Guayaquil",
    "coords": [
      -2.17,
      -79.92
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Halifax",
    "coords": [
      44.65,
      -63.57
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Havana",
    "coords": [
      23.11,
      -82.37
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Indiana/Indianapolis",
    "coords": [
      39.77,
      -86.16
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Jamaica",
    "coords": [
      18.11,
      -77.3
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Juneau",
    "coords": [
      58.3,
      -134.42
    ],
    "etcgmtOffsetKey": "UTC-09:00"
  },
  {
    "tz": "America/La_Paz",
    "coords": [
      -16.5,
      -68.15
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Lima",
    "coords": [
      -12.05,
      -77.03
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Los_Angeles",
    "coords": [
      34.05,
      -118.24
    ],
    "etcgmtOffsetKey": "UTC-08:00"
  },
  {
    "tz": "America/Managua",
    "coords": [
      12.11,
      -86.27
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "America/Manaus",
    "coords": [
      -3.12,
      -60.02
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Mazatlan",
    "coords": [
      23.22,
      -106.42
    ],
    "etcgmtOffsetKey": "UTC-07:00"
  },
  {
    "tz": "America/Mexico_City",
    "coords": [
      19.43,
      -99.13
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "America/Miquelon",
    "coords": [
      47.1,
      -56.38
    ],
    "etcgmtOffsetKey": "UTC-03:00"
  },
  {
    "tz": "America/Montevideo",
    "coords": [
      -34.88,
      -56.16
    ],
    "etcgmtOffsetKey": "UTC-03:00"
  },
  {
    "tz": "America/Nassau",
    "coords": [
      25.05,
      -77.35
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/New_York",
    "coords": [
      40.71,
      -74.01
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Noronha",
    "coords": [
      -3.85,
      -32.42
    ],
    "etcgmtOffsetKey": "UTC-02:00"
  },
  {
    "tz": "America/Panama",
    "coords": [
      8.97,
      -79.53
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Paramaribo",
    "coords": [
      5.85,
      -55.17
    ],
    "etcgmtOffsetKey": "UTC-03:00"
  },
  {
    "tz": "America/Phoenix",
    "coords": [
      33.45,
      -112.07
    ],
    "etcgmtOffsetKey": "UTC-07:00"
  },
  {
    "tz": "America/Port-au-Prince",
    "coords": [
      18.54,
      -72.34
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Porto_Velho",
    "coords": [
      -8.76,
      -63.9
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Puerto_Rico",
    "coords": [
      18.47,
      -66.12
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Recife",
    "coords": [
      -8.05,
      -34.87
    ],
    "etcgmtOffsetKey": "UTC-03:00"
  },
  {
    "tz": "America/Regina",
    "coords": [
      50.45,
      -104.62
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "America/Rio_Branco",
    "coords": [
      -9.97,
      -67.81
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Santiago",
    "coords": [
      -33.45,
      -70.67
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Santo_Domingo",
    "coords": [
      18.49,
      -69.93
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "America/Sao_Paulo",
    "coords": [
      -23.55,
      -46.63
    ],
    "etcgmtOffsetKey": "UTC-03:00"
  },
  {
    "tz": "America/St_Johns",
    "coords": [
      47.56,
      -52.71
    ],
    "etcgmtOffsetKey": "UTC-03:30"
  },
  {
    "tz": "America/Tegucigalpa",
    "coords": [
      14.07,
      -87.19
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "America/Tijuana",
    "coords": [
      32.53,
      -117.02
    ],
    "etcgmtOffsetKey": "UTC-08:00"
  },
  {
    "tz": "America/Toronto",
    "coords": [
      43.65,
      -79.38
    ],
    "etcgmtOffsetKey": "UTC-05:00"
  },
  {
    "tz": "America/Vancouver",
    "coords": [
      49.26,
      -123.11
    ],
    "etcgmtOffsetKey": "UTC-08:00"
  },
  {
    "tz": "America/Winnipeg",
    "coords": [
      49.9,
      -97.14
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "Asia/Almaty",
    "coords": [
      43.24,
      76.95
    ],
    "etcgmtOffsetKey": "UTC+06:00"
  },
  {
    "tz": "Asia/Amman",
    "coords": [
      31.96,
      35.95
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Asia/Baghdad",
    "coords": [
      33.31,
      44.37
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Asia/Baku",
    "coords": [
      40.41,
      49.87
    ],
    "etcgmtOffsetKey": "UTC+04:00"
  },
  {
    "tz": "Asia/Bangkok",
    "coords": [
      13.76,
      100.5
    ],
    "etcgmtOffsetKey": "UTC+07:00"
  },
  {
    "tz": "Asia/Beirut",
    "coords": [
      33.89,
      35.5
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Asia/Bishkek",
    "coords": [
      42.87,
      74.59
    ],
    "etcgmtOffsetKey": "UTC+06:00"
  },
  {
    "tz": "Asia/Brunei",
    "coords": [
      4.93,
      114.95
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Asia/Colombo",
    "coords": [
      6.93,
      79.85
    ],
    "etcgmtOffsetKey": "UTC+05:30"
  },
  {
    "tz": "Asia/Damascus",
    "coords": [
      33.51,
      36.29
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Asia/Dhaka",
    "coords": [
      23.81,
      90.41
    ],
    "etcgmtOffsetKey": "UTC+06:00"
  },
  {
    "tz": "Asia/Dubai",
    "coords": [
      25.2,
      55.27
    ],
    "etcgmtOffsetKey": "UTC+04:00"
  },
  {
    "tz": "Asia/Dushanbe",
    "coords": [
      38.56,
      68.77
    ],
    "etcgmtOffsetKey": "UTC+05:00"
  },
  {
    "tz": "Asia/Gaza",
    "coords": [
      31.5,
      34.47
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Asia/Ho_Chi_Minh",
    "coords": [
      10.82,
      106.63
    ],
    "etcgmtOffsetKey": "UTC+07:00"
  },
  {
    "tz": "Asia/Hong_Kong",
    "coords": [
      22.28,
      114.16
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Asia/Irkutsk",
    "coords": [
      52.29,
      104.3
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Asia/Jakarta",
    "coords": [
      -6.21,
      106.85
    ],
    "etcgmtOffsetKey": "UTC+07:00"
  },
  {
    "tz": "Asia/Jerusalem",
    "coords": [
      31.77,
      35.22
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Asia/Kabul",
    "coords": [
      34.53,
      69.17
    ],
    "etcgmtOffsetKey": "UTC+04:30"
  },
  {
    "tz": "Asia/Karachi",
    "coords": [
      24.86,
      67.01
    ],
    "etcgmtOffsetKey": "UTC+05:00"
  },
  {
    "tz": "Asia/Kathmandu",
    "coords": [
      27.72,
      85.32
    ],
    "etcgmtOffsetKey": "UTC+05:45"
  },
  {
    "tz": "Asia/Kolkata",
    "coords": [
      28.61,
      77.21
    ],
    "etcgmtOffsetKey": "UTC+05:30"
  },
  {
    "tz": "Asia/Krasnoyarsk",
    "coords": [
      56.01,
      92.87
    ],
    "etcgmtOffsetKey": "UTC+07:00"
  },
  {
    "tz": "Asia/Kuala_Lumpur",
    "coords": [
      3.14,
      101.69
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Asia/Kuwait",
    "coords": [
      29.38,
      47.99
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Asia/Macau",
    "coords": [
      22.2,
      113.55
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Asia/Magadan",
    "coords": [
      59.57,
      150.8
    ],
    "etcgmtOffsetKey": "UTC+11:00"
  },
  {
    "tz": "Asia/Manila",
    "coords": [
      14.6,
      120.98
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Asia/Muscat",
    "coords": [
      23.59,
      58.39
    ],
    "etcgmtOffsetKey": "UTC+04:00"
  },
  {
    "tz": "Asia/Nicosia",
    "coords": [
      35.17,
      33.37
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Asia/Novosibirsk",
    "coords": [
      55.03,
      82.92
    ],
    "etcgmtOffsetKey": "UTC+07:00"
  },
  {
    "tz": "Asia/Omsk",
    "coords": [
      54.99,
      73.37
    ],
    "etcgmtOffsetKey": "UTC+06:00"
  },
  {
    "tz": "Asia/Phnom_Penh",
    "coords": [
      11.56,
      104.92
    ],
    "etcgmtOffsetKey": "UTC+07:00"
  },
  {
    "tz": "Asia/Pyongyang",
    "coords": [
      39.02,
      125.75
    ],
    "etcgmtOffsetKey": "UTC+09:00"
  },
  {
    "tz": "Asia/Qatar",
    "coords": [
      25.29,
      51.53
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Asia/Riyadh",
    "coords": [
      24.69,
      46.72
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Asia/Sakhalin",
    "coords": [
      46.96,
      142.73
    ],
    "etcgmtOffsetKey": "UTC+11:00"
  },
  {
    "tz": "Asia/Samarkand",
    "coords": [
      39.65,
      66.96
    ],
    "etcgmtOffsetKey": "UTC+05:00"
  },
  {
    "tz": "Asia/Seoul",
    "coords": [
      37.57,
      126.98
    ],
    "etcgmtOffsetKey": "UTC+09:00"
  },
  {
    "tz": "Asia/Shanghai",
    "coords": [
      31.23,
      121.47
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Asia/Singapore",
    "coords": [
      1.35,
      103.82
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Asia/Taipei",
    "coords": [
      25.03,
      121.57
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Asia/Tashkent",
    "coords": [
      41.3,
      69.24
    ],
    "etcgmtOffsetKey": "UTC+05:00"
  },
  {
    "tz": "Asia/Tbilisi",
    "coords": [
      41.72,
      44.79
    ],
    "etcgmtOffsetKey": "UTC+04:00"
  },
  {
    "tz": "Asia/Tehran",
    "coords": [
      35.69,
      51.39
    ],
    "etcgmtOffsetKey": "UTC+03:30"
  },
  {
    "tz": "Asia/Thimphu",
    "coords": [
      27.47,
      89.64
    ],
    "etcgmtOffsetKey": "UTC+06:00"
  },
  {
    "tz": "Asia/Tokyo",
    "coords": [
      35.68,
      139.69
    ],
    "etcgmtOffsetKey": "UTC+09:00"
  },
  {
    "tz": "Asia/Ulaanbaatar",
    "coords": [
      47.92,
      106.92
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Asia/Vladivostok",
    "coords": [
      43.12,
      131.87
    ],
    "etcgmtOffsetKey": "UTC+10:00"
  },
  {
    "tz": "Asia/Yakutsk",
    "coords": [
      62.03,
      129.73
    ],
    "etcgmtOffsetKey": "UTC+09:00"
  },
  {
    "tz": "Asia/Yangon",
    "coords": [
      16.87,
      96.2
    ],
    "etcgmtOffsetKey": "UTC+06:30"
  },
  {
    "tz": "Asia/Yekaterinburg",
    "coords": [
      56.84,
      60.6
    ],
    "etcgmtOffsetKey": "UTC+05:00"
  },
  {
    "tz": "Asia/Yerevan",
    "coords": [
      40.18,
      44.51
    ],
    "etcgmtOffsetKey": "UTC+04:00"
  },
  {
    "tz": "Atlantic/Azores",
    "coords": [
      38.72,
      -27.22
    ],
    "etcgmtOffsetKey": "UTC-01:00"
  },
  {
    "tz": "Atlantic/Bermuda",
    "coords": [
      32.29,
      -64.78
    ],
    "etcgmtOffsetKey": "UTC-04:00"
  },
  {
    "tz": "Atlantic/Canary",
    "coords": [
      28.1,
      -15.41
    ],
    "etcgmtOffsetKey": "UTC+00:00"
  },
  {
    "tz": "Atlantic/Cape_Verde",
    "coords": [
      14.93,
      -23.51
    ],
    "etcgmtOffsetKey": "UTC-01:00"
  },
  {
    "tz": "Atlantic/Reykjavik",
    "coords": [
      64.14,
      -21.94
    ],
    "etcgmtOffsetKey": "UTC+00:00"
  },
  {
    "tz": "Atlantic/South_Georgia",
    "coords": [
      -54.27,
      -36.51
    ],
    "etcgmtOffsetKey": "UTC-02:00"
  },
  {
    "tz": "Australia/Adelaide",
    "coords": [
      -34.93,
      138.6
    ],
    "etcgmtOffsetKey": "UTC+09:30"
  },
  {
    "tz": "Australia/Brisbane",
    "coords": [
      -27.47,
      153.03
    ],
    "etcgmtOffsetKey": "UTC+10:00"
  },
  {
    "tz": "Australia/Broken_Hill",
    "coords": [
      -31.95,
      141.47
    ],
    "etcgmtOffsetKey": "UTC+09:30"
  },
  {
    "tz": "Australia/Darwin",
    "coords": [
      -12.46,
      130.84
    ],
    "etcgmtOffsetKey": "UTC+09:30"
  },
  {
    "tz": "Australia/Eucla",
    "coords": [
      -31.68,
      128.88
    ],
    "etcgmtOffsetKey": "UTC+08:45"
  },
  {
    "tz": "Australia/Hobart",
    "coords": [
      -42.88,
      147.33
    ],
    "etcgmtOffsetKey": "UTC+10:00"
  },
  {
    "tz": "Australia/Lord_Howe",
    "coords": [
      -31.55,
      159.08
    ],
    "etcgmtOffsetKey": "UTC+10:30"
  },
  {
    "tz": "Australia/Melbourne",
    "coords": [
      -37.81,
      144.96
    ],
    "etcgmtOffsetKey": "UTC+10:00"
  },
  {
    "tz": "Australia/Perth",
    "coords": [
      -31.95,
      115.86
    ],
    "etcgmtOffsetKey": "UTC+08:00"
  },
  {
    "tz": "Australia/Sydney",
    "coords": [
      -33.87,
      151.21
    ],
    "etcgmtOffsetKey": "UTC+10:00"
  },
  {
    "tz": "Etc/UTC",
    "coords": [
      0,
      0
    ],
    "etcgmtOffsetKey": "UTC+00:00"
  },
  {
    "tz": "Europe/Amsterdam",
    "coords": [
      52.37,
      4.9
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Andorra",
    "coords": [
      42.51,
      1.52
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Athens",
    "coords": [
      37.98,
      23.73
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Europe/Belgrade",
    "coords": [
      44.79,
      20.47
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Berlin",
    "coords": [
      52.52,
      13.41
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Bratislava",
    "coords": [
      48.15,
      17.11
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Brussels",
    "coords": [
      50.85,
      4.35
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Bucharest",
    "coords": [
      44.43,
      26.1
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Europe/Budapest",
    "coords": [
      47.5,
      19.04
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Chisinau",
    "coords": [
      47.01,
      28.86
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Europe/Copenhagen",
    "coords": [
      55.68,
      12.57
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Dublin",
    "coords": [
      53.33,
      -6.25
    ],
    "etcgmtOffsetKey": "UTC+00:00"
  },
  {
    "tz": "Europe/Helsinki",
    "coords": [
      60.17,
      24.94
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Europe/Kaliningrad",
    "coords": [
      54.71,
      20.45
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Europe/Kyiv",
    "coords": [
      50.45,
      30.52
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Europe/Lisbon",
    "coords": [
      38.72,
      -9.14
    ],
    "etcgmtOffsetKey": "UTC+00:00"
  },
  {
    "tz": "Europe/Ljubljana",
    "coords": [
      46.06,
      14.51
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/London",
    "coords": [
      51.51,
      -0.13
    ],
    "etcgmtOffsetKey": "UTC+00:00"
  },
  {
    "tz": "Europe/Luxembourg",
    "coords": [
      49.61,
      6.13
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Madrid",
    "coords": [
      40.42,
      -3.7
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Malta",
    "coords": [
      35.9,
      14.51
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Minsk",
    "coords": [
      53.9,
      27.57
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Europe/Monaco",
    "coords": [
      43.73,
      7.42
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Moscow",
    "coords": [
      55.76,
      37.62
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Europe/Oslo",
    "coords": [
      59.91,
      10.75
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Paris",
    "coords": [
      48.86,
      2.35
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Prague",
    "coords": [
      50.08,
      14.42
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Riga",
    "coords": [
      56.95,
      24.11
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Europe/Rome",
    "coords": [
      41.9,
      12.5
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Samara",
    "coords": [
      53.2,
      50.15
    ],
    "etcgmtOffsetKey": "UTC+04:00"
  },
  {
    "tz": "Europe/Sarajevo",
    "coords": [
      43.86,
      18.41
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Simferopol",
    "coords": [
      44.95,
      34.1
    ],
    "etcgmtOffsetKey": "UTC+03:00"
  },
  {
    "tz": "Europe/Sofia",
    "coords": [
      42.7,
      23.32
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Europe/Stockholm",
    "coords": [
      59.33,
      18.07
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Tallinn",
    "coords": [
      59.44,
      24.75
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Europe/Tirane",
    "coords": [
      41.33,
      19.82
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Vienna",
    "coords": [
      48.21,
      16.37
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Vilnius",
    "coords": [
      54.69,
      25.28
    ],
    "etcgmtOffsetKey": "UTC+02:00"
  },
  {
    "tz": "Europe/Volgograd",
    "coords": [
      48.72,
      44.5
    ],
    "etcgmtOffsetKey": "UTC+04:00"
  },
  {
    "tz": "Europe/Warsaw",
    "coords": [
      52.23,
      21.01
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Zagreb",
    "coords": [
      45.81,
      15.98
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Europe/Zurich",
    "coords": [
      47.38,
      8.54
    ],
    "etcgmtOffsetKey": "UTC+01:00"
  },
  {
    "tz": "Indian/Maldives",
    "coords": [
      4.18,
      73.51
    ],
    "etcgmtOffsetKey": "UTC+05:00"
  },
  {
    "tz": "Indian/Mauritius",
    "coords": [
      -20.16,
      57.5
    ],
    "etcgmtOffsetKey": "UTC+04:00"
  },
  {
    "tz": "Indian/Reunion",
    "coords": [
      -20.88,
      55.45
    ],
    "etcgmtOffsetKey": "UTC+04:00"
  },
  {
    "tz": "Pacific/Auckland",
    "coords": [
      -36.85,
      174.76
    ],
    "etcgmtOffsetKey": "UTC+12:00"
  },
  {
    "tz": "Pacific/Chatham",
    "coords": [
      -43.88,
      -176.46
    ],
    "etcgmtOffsetKey": "UTC+12:45"
  },
  {
    "tz": "Pacific/Easter",
    "coords": [
      -27.12,
      -109.35
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "Pacific/Fiji",
    "coords": [
      -18.14,
      178.44
    ],
    "etcgmtOffsetKey": "UTC+12:00"
  },
  {
    "tz": "Pacific/Galapagos",
    "coords": [
      -0.75,
      -90.3
    ],
    "etcgmtOffsetKey": "UTC-06:00"
  },
  {
    "tz": "Pacific/Gambier",
    "coords": [
      -23.12,
      -134.97
    ],
    "etcgmtOffsetKey": "UTC-09:00"
  },
  {
    "tz": "Pacific/Guadalcanal",
    "coords": [
      -9.43,
      160.05
    ],
    "etcgmtOffsetKey": "UTC+11:00"
  },
  {
    "tz": "Pacific/Guam",
    "coords": [
      13.44,
      144.79
    ],
    "etcgmtOffsetKey": "UTC+10:00"
  },
  {
    "tz": "Pacific/Honolulu",
    "coords": [
      21.31,
      -157.86
    ],
    "etcgmtOffsetKey": "UTC-10:00"
  },
  {
    "tz": "Pacific/Marquesas",
    "coords": [
      -9.78,
      -139.03
    ],
    "etcgmtOffsetKey": "UTC-09:30"
  },
  {
    "tz": "Pacific/Noumea",
    "coords": [
      -22.28,
      166.46
    ],
    "etcgmtOffsetKey": "UTC+11:00"
  },
  {
    "tz": "Pacific/Pago_Pago",
    "coords": [
      -14.28,
      -170.7
    ],
    "etcgmtOffsetKey": "UTC-11:00"
  },
  {
    "tz": "Pacific/Port_Moresby",
    "coords": [
      -6.21,
      147
    ],
    "etcgmtOffsetKey": "UTC+10:00"
  },
  {
    "tz": "Pacific/Tahiti",
    "coords": [
      -17.53,
      -149.57
    ],
    "etcgmtOffsetKey": "UTC-10:00"
  },
  {
    "tz": "Pacific/Tongatapu",
    "coords": [
      -21.21,
      -175.2
    ],
    "etcgmtOffsetKey": "UTC+13:00"
  }
];
